# Generated by Django 4.1.7 on 2023-02-16 06:27

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="lasstName",
            new_name="lastName",
        ),
        migrations.AlterField(
            model_name="employee",
            name="contactNumber",
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
    ]
