# Generated by Django 4.1.7 on 2023-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employee_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="Barangay",
            field=models.CharField(default="fairview", max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="City",
            field=models.CharField(default="quezon city", max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="Country",
            field=models.CharField(default="philippines", max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="Department",
            field=models.CharField(default="IT", max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="EmployeeStatus",
            field=models.CharField(default="active", max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="HouseNumber",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="Job",
            field=models.CharField(default="IT", max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="Religion",
            field=models.CharField(default="christian", max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="TIN",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="Zip",
            field=models.IntegerField(default=0),
        ),
    ]
